In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
data = pd.read_csv(r'C:\Users\saisa\Downloads\student_dropout.csv')
data.head()

,School,Gender,Age,Address,Family_Size,Parental_Status,Mother_Education,Father_Education,Mother_Job,Father_Job,...,Free_Time,Going_Out,Weekend_Alcohol_Consumption,Weekday_Alcohol_Consumption,Health_Status,Number_of_Absences,Grade_1,Grade_2,Final_Grade,Dropped_Out
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,False
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,False
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,False
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,False


In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   School                       649 non-null    object
 1   Gender                       649 non-null    object
 2   Age                          649 non-null    int64 
 3   Address                      649 non-null    object
 4   Family_Size                  649 non-null    object
 5   Parental_Status              649 non-null    object
 6   Mother_Education             649 non-null    int64 
 7   Father_Education             649 non-null    int64 
 8   Mother_Job                   649 non-null    object
 9   Father_Job                   649 non-null    object
 10  Reason_for_Choosing_School   649 non-null    object
 11  Guardian                     649 non-null    object
 12  Travel_Time                  649 non-null    int64 
 13  Study_Time                   649 no

In [7]:
data.isna().sum()

School                         0
Gender                         0
Age                            0
Address                        0
Family_Size                    0
Parental_Status                0
Mother_Education               0
Father_Education               0
Mother_Job                     0
Father_Job                     0
Reason_for_Choosing_School     0
Guardian                       0
Travel_Time                    0
Study_Time                     0
Number_of_Failures             0
School_Support                 0
Family_Support                 0
Extra_Paid_Class               0
Extra_Curricular_Activities    0
Attended_Nursery               0
Wants_Higher_Education         0
Internet_Access                0
In_Relationship                0
Family_Relationship            0
Free_Time                      0
Going_Out                      0
Weekend_Alcohol_Consumption    0
Weekday_Alcohol_Consumption    0
Health_Status                  0
Number_of_Absences             0
Grade_1   

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

le = LabelEncoder()
for column in data.columns:
    if data[column].dtype == type(object):
        data[column] = le.fit_transform(data[column])

scaler = StandardScaler()
for column in data.columns:
    if data[column].dtype == type(int) or data[column].dtype == type(float):
        data[column] = scaler.fit_transform(data[[column]])

X = data.drop('Dropped_Out', axis=1)
y = data['Dropped_Out']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

models = {
    'Random Forest': RandomForestClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'AdaBoost': AdaBoostClassifier(random_state=42),
    'Extra Trees': ExtraTreesClassifier(random_state=42),
    'Bagging': BaggingClassifier(random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Logistic Regression': LogisticRegression(random_state=42),
    'SVC': SVC(random_state=42),
    'XGBoost': XGBClassifier(random_state=42),
    'CatBoost': CatBoostClassifier(random_state=42, verbose=False),
    'LightGBM': LGBMClassifier(random_state=42, verbose=-1),
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(name)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print("------------------------------------")

Random Forest
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy                           1.00       130
   macro avg       1.00      1.00      1.00       130
weighted avg       1.00      1.00      1.00       130

[[115   0]
 [  0  15]]
------------------------------------
Gradient Boosting
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy                           1.00       130
   macro avg       1.00      1.00      1.00       130
weighted avg       1.00      1.00      1.00       130

[[115   0]
 [  0  15]]
------------------------------------
AdaBoost
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy         

C:\Users\saisa\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Extra Trees
              precision    recall  f1-score   support

       False       0.97      0.99      0.98       115
        True       0.92      0.73      0.81        15

    accuracy                           0.96       130
   macro avg       0.94      0.86      0.90       130
weighted avg       0.96      0.96      0.96       130

[[114   1]
 [  4  11]]
------------------------------------
Bagging
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy                           1.00       130
   macro avg       1.00      1.00      1.00       130
weighted avg       1.00      1.00      1.00       130

[[115   0]
 [  0  15]]
------------------------------------
Decision Tree
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy                

C:\Users\saisa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy                           1.00       130
   macro avg       1.00      1.00      1.00       130
weighted avg       1.00      1.00      1.00       130

[[115   0]
 [  0  15]]
------------------------------------
SVC
              precision    recall  f1-score   support

       False       0.96      1.00      0.98       115
        True       1.00      0.67      0.80        15

    accuracy                           0.96       130
   macro avg       0.98      0.83      0.89       130
weighted avg       0.96      0.96      0.96       130

[[115   0]
 [  5  10]]
------------------------------------
XGBoost
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       115
        True       1.00      1.00      1.00        15

    accuracy                  

## PyTorch

In [14]:
import torch
from torch import nn, optim

X_pytorch = data.drop('Dropped_Out', axis=1).values
y_pytorch = data['Dropped_Out'].values

X_torch = torch.tensor(X_pytorch, dtype=torch.float)
y_torch = torch.tensor(y_pytorch, dtype=torch.float).view(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X_torch, y_torch, test_size=0.2, random_state=42)


class StudentDropout(nn.Module):
    def __init__(self, input_size):
        super(StudentDropout, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))
        return x

model = StudentDropout(X_train.shape[1])

In [16]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)
l2_lambda = 0.01

for epoch in range(5000):
    model.train()
    optimizer.zero_grad()
    output = model(X_train)
    loss = criterion(output, y_train) + l2_lambda * sum(p.pow(2.0).sum() for p in model.parameters())
    loss.backward()
    optimizer.step()

model.eval()
with torch.no_grad():
    output = model(X_test)
    predicted = (output > 0.5).float()
    accuracy = (predicted == y_test).float().mean()
    print(f'Accuracy: {accuracy.item() * 100}%')

Accuracy: 91.5384590625763%
